#:schema node_modules/wrangler/config-schema.json
name = "sveltekit-cf"
compatibility_date = "2024-04-05"

compatibility_flags = [ "nodejs_compat" ]

pages_build_output_dir = "/.svelte-kit"

# [vars]
# MY_VARIABLE = "production_value"

[[d1_databases]]
binding = "DB"
database_name = "test-db"
database_id = "0e23e91e-b087-4f3e-906f-87f28dc26d13"
migrations_dir = "./drizzle/migrations"

[[kv_namespaces]]
binding = "KV"
id = "f9a17519d43244f880edbc4244d29aea"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"
